### PR TITLE
JNCI Edits: Signaling iOS Swift

### PR DESCRIPTION
**Pull request by jamesneimanconsulting**
@sidsharma27 Kindly review and merge if approved.

### CODE REVIEW

**Comment by jamesneimanconsulting** [comment]
@sidsharma27 added chinese link. Please merge in.

**Review by plutoless — CHANGES_REQUESTED** [review]
@sidsharma27  as we agreed, pls avoid putting too long line by line guide in readme index. instead we should provide a guide.md and put these explanations there. And then put a link to this guide.md from index readme.md

**Comment by jamesneimanconsulting** [comment]
@sidsharma27 , @plutoless Can I please see an example of what you mean?

**Comment by plutoless** [comment]
@jamesneimanconsulting the suggested format is shown as below,

readme.md
1. Summary or description of this repo
2. Prerequisite ( sdks, versions, platform)
3. Quick start to run the demo
4. Additional info (e.g. how to integrate rn from scratch, depends on project, optional)
5. Resources (link to issues, docs, **guide** <- put a link here to guide.md)
6. License

guide.md
put your line by line code explanation + images in here

if still not clear maybe you can talk to @sidsharma27  directly? Or we may schedule a call for this one.

**Comment by jamesneimanconsulting** [comment]
@plutoless , @sidsharma27 I have refactored using a guide.md file, and have updated this branch.

**Review by plutoless — APPROVED** [review]

**Pull request merged**
